Repository Initiate-Colorado/initiate-co-ui, pull requests merged in 2020-09, with the labels that each got.

#11 Users and Subscribers
  api/.babelrc
  api/.env
  api/.gitignore
  api/.sequelizerc
  api/package-lock.json
  api/package.json
  api/public/images/stock/belt-female.jpg
  api/public/images/stock/belt-male.jpg
  api/public/images/stock/t-shirt-female-1.jpg
  api/public/images/stock/t-shirt-female-2.jpg
  api/public/images/stock/t-shirt-male-1.jpg
  api/public/images/stock/t-shirt-male-2.jpg
  api/public/images/stock/watch-female.jpg
  api/public/images/stock/watch-male.jpg
  api/public/images/uploads/.gitkeep
  api/server.js
  api/src/config/env.js
  api/src/config/server.json
  api/src/index.js
  api/src/migrations/1-user.js
  api/src/migrations/2-subscribers.js
  api/src/modules/subscriber/model.js
  api/src/modules/subscriber/mutations.js
  api/src/modules/subscriber/query.js
  api/src/modules/subscriber/resolvers.js
  api/src/modules/subscriber/types.js
  api/src/modules/user/model.js
  api/src/modules/user/mutations.js
  api/src/modules/user/query.js
  api/src/modules/user/resolvers.js
  api/src/modules/user/types.js
  api/src/seeders/3-user.js
  api/src/setup/database.js
  api/src/setup/graphql.js
  api/src/setup/load-modules.js
  api/src/setup/models.js
  api/src/setup/schema/index.js
  api/src/setup/schema/mutations.js
  api/src/setup/schema/queries.js
  api/src/setup/start-server.js
  api/src/setup/upload.js
  package-lock.json
  package.json
Labels: enhancement

#19 Ballots and ballot_process database
  api/src/migrations/3-ballot_process.js
  api/src/migrations/4-ballots.js
  api/src/modules/ballot_process/model.js
  api/src/modules/ballot_process/mutations.js
  api/src/modules/ballot_process/query.js
  api/src/modules/ballot_process/resolvers.js
  api/src/modules/ballot_process/types.js
  api/src/modules/ballots/model.js
  api/src/modules/ballots/mutations.js
  api/src/modules/ballots/query.js
  api/src/modules/ballots/resolvers.js
  api/src/modules/ballots/types.js
  api/src/seeders/4-ballots.js
  api/src/setup/authentication.js
  api/src/setup/models.js
  api/src/setup/schema/mutations.js
  api/src/setup/schema/queries.js
Labels: DB Setup, MVP

#30 Update user table and add ballot table
  api/src/migrations/1-user.js
  api/src/migrations/4-ballots.js
  api/src/modules/ballots/model.js
  api/src/modules/ballots/mutations.js
  api/src/modules/ballots/query.js
  api/src/modules/ballots/resolvers.js
  api/src/modules/ballots/types.js
  api/src/modules/user/model.js
  api/src/modules/user/mutations.js
  api/src/modules/user/resolvers.js
  api/src/modules/user/types.js
  api/src/seeders/4-user.js
  api/src/seeders/6-ballots.js
Labels: DB Setup, MVP, enhancement

#40 Feature/proposal
  src/components/App/App.css
  src/components/App/App.js
  src/components/BeginInitiative/BeginInitiative.css
  src/components/BeginInitiative/BeginInitiative.js
  src/components/Info/Info.css
  src/components/Info/Info.js
  src/components/Process/Process.css
  src/components/Process/Process.js
  src/components/Process/Process.test.js
  src/components/StepTracker/StepTracker.css
  src/components/StepTracker/StepTracker.js
  src/components/StepTracker/component.js
  src/components/StepTracker/reducer.js
  src/components/mocks/StepEight.js
  src/components/mocks/StepEleven.js
  src/components/mocks/StepFive.js
  src/components/mocks/StepFour.js
  src/components/mocks/StepFourteen.js
  src/components/mocks/StepNine.js
  src/components/mocks/StepOne.js
  src/components/mocks/StepSeven.js
  src/components/mocks/StepSix.js
  src/components/mocks/StepTen.js
  src/components/mocks/StepThirteen.js
  src/components/mocks/StepThree.js
  src/components/mocks/StepTwelve.js
  src/components/mocks/StepTwo.js
  src/pull_request-template.md
Labels: styling

#42 Feature/research page api calls
  src/components/Official/Official.js
  src/components/Proposed/Proposed.js
Labels: enhancement

#44 Feature/user steps
  public/manifest.json
  pull_request-template.md
  src/components/App/App.css
  src/components/App/App.js
  src/components/BeginInitiative/BeginInitiative.css
  src/components/BeginInitiative/BeginInitiative.js
  src/components/Info/Info.css
  src/components/Info/Info.js
  src/components/Login/Login.js
  src/components/Nav/Nav.css
  src/components/Nav/Nav.js
  src/components/Signup/Signup.js
  src/components/StepTracker/StepTracker.css
  src/components/StepTracker/reducer.js
  src/components/mocks/StepEleven.js
  src/components/mocks/StepFourteen.js
  src/components/mocks/StepOne.js
  src/components/mocks/StepThirteen.js
  src/components/mocks/StepTwelve.js
  src/components/steps/StepEight.js
  src/components/steps/StepEight.test.js
  src/components/steps/StepEleven.js
  src/components/steps/StepEleven.test.js
  src/components/steps/StepFive.js
  src/components/steps/StepFive.test.js
  src/components/steps/StepFour.js
  src/components/steps/StepFour.test.js
  src/components/steps/StepFourteen.js
  src/components/steps/StepFourteen.test.js
  src/components/steps/StepNine.js
  src/components/steps/StepNine.test.js
  src/components/steps/StepOne.js
  src/components/steps/StepOne.test.js
  src/components/steps/StepSeven.js
  src/components/steps/StepSeven.test.js
  src/components/steps/StepSix.js
  src/components/steps/StepSix.test.js
  src/components/steps/StepTen.js
  src/components/steps/StepTen.test.js
  src/components/steps/StepThirteen.js
  src/components/steps/StepThirteen.test.js
  src/components/steps/StepThree.js
  src/components/steps/StepThree.test.js
  src/components/steps/StepTwelve.js
  src/components/steps/StepTwelve.test.js
  src/components/steps/StepTwo.js
  src/components/steps/StepTwo.test.js
  travis.yml
Labels: MVP, enhancement, styling

#51 Feature/rewrite
  src/components/steps/StepEight.js
  src/components/steps/StepEleven.js
  src/components/steps/StepFive.js
  src/components/steps/StepFour.js
  src/components/steps/StepFourteen.js
  src/components/steps/StepNine.js
  src/components/steps/StepOne.js
  src/components/steps/StepSeven.js
  src/components/steps/StepSix.js
  src/components/steps/StepTen.js
  src/components/steps/StepThirteen.js
  src/components/steps/StepThree.js
  src/components/steps/StepTwelve.js
  src/components/steps/StepTwo.js
Labels: enhancement
